version: "3"

services:
    server:
        container_name: server
        restart: always
        build: ./server
        ports:
            - "8000:8000"
        command: gunicorn -w 1 -b :8000 dfile:app

    nginx:
        container_name: nginx
        restart: always
        build: ./nginx
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - server
