"""empty message

Revision ID: 0cd36ecdd937
Revises: None
Create Date: 2016-11-01 05:25:42.691768

"""

# revision identifiers, used by Alembic.
revision = '0cd36ecdd937'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(50), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    ### end Alembic commands ###
