"""20200516.init

Revision ID: 376aa0821605
Revises: 
Create Date: 2020-05-16 15:14:20.031867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376aa0821605'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('dl_num', sa.Integer(), nullable=True),
    sa.Column('hash', sa.String(length=46), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('lastdl_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_hash'), 'file', ['hash'], unique=False)
    op.create_index(op.f('ix_file_path'), 'file', ['path'], unique=False)
    op.create_index(op.f('ix_file_slug'), 'file', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_slug'), table_name='file')
    op.drop_index(op.f('ix_file_path'), table_name='file')
    op.drop_index(op.f('ix_file_hash'), table_name='file')
    op.drop_table('file')
    # ### end Alembic commands ###
