"""20200516.hash

Revision ID: 6284f065d4a2
Revises: 852ee054f5fd
Create Date: 2020-05-16 11:38:09.003853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6284f065d4a2'
down_revision = '852ee054f5fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('hash', sa.String(length=46), nullable=True))
    op.create_index(op.f('ix_file_hash'), 'file', ['hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_hash'), table_name='file')
    op.drop_column('file', 'hash')
    # ### end Alembic commands ###
