"""20200515.init

Revision ID: 70eccf8c5ddd
Revises: 
Create Date: 2020-05-15 22:16:47.421138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70eccf8c5ddd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=256), nullable=True),
    sa.Column('dl_num', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('lastdl_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_slug'), 'file', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_slug'), table_name='file')
    op.drop_table('file')
    # ### end Alembic commands ###
