"""20200516.source

Revision ID: 852ee054f5fd
Revises: 70eccf8c5ddd
Create Date: 2020-05-16 09:23:39.496374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852ee054f5fd'
down_revision = '70eccf8c5ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('source', sa.String(length=32), nullable=True))
    op.alter_column('file', 'path',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.create_index(op.f('ix_file_path'), 'file', ['path'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_path'), table_name='file')
    op.alter_column('file', 'path',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.drop_column('file', 'source')
    # ### end Alembic commands ###
